CREATE TABLE employees_copy_new (
	employeeID NUMBER,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	department VARCHAR(50),
	salary NUMBER 
);
DROP TABLE EMPLOYEES_COPY_NEW ;

INSERT INTO EMPLOYEES_COPY_NEW VALUES (101,'John1','Doe1','HR',20000);
INSERT INTO EMPLOYEES_COPY_NEW VALUES (102,'John2','Doe2','IT',50000);
INSERT INTO EMPLOYEES_COPY_NEW VALUES (103,'John3','Doe3','CS',40000);
INSERT INTO EMPLOYEES_COPY_NEW VALUES (104,'John4','Doe4','IT',10000);
INSERT INTO EMPLOYEES_COPY_NEW VALUES (105,'John5','Doe5','ZX',30000);
INSERT INTO EMPLOYEES_COPY_NEW VALUES (106,'John6','Doe6','HR',60000);
UPDATE EMPLOYEES_COPY_NEW SET salary= 60000 WHERE EMPLOYEEID =101;
DELETE EMPLOYEES_COPY_NEW  WHERE department='ZX';
SELECT * FROM EMPLOYEES_COPY_NEW WHERE DEPARTMENT='IT';
SELECT employeeID,first_name || ' ' || last_name AS full_name,department,salary FROM EMPLOYEES_COPY_NEW; 
