CREATE TABLE PATIENTS(
	patient_id number PRIMARY KEY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	Gender VARCHAR(255),
	Date_of_birth DATE,
	phone VARCHAR(255),
	Address VARCHAR(255) 
);

CREATE TABLE  Departments_new(
	Department_id number PRIMARY KEY ,
	Name varchar(255),
	lacation varchar(255)
);

CREATE TABLE Medicines(
	Medicine_id NUMBER PRIMARY KEY ,
	name VARCHAR(255),
	price NUMBER,
	Stock_quality VARCHAR(255)
);
CREATE TABLE Doctors (
	doctor_id number(10) PRIMARY KEY ,
	fIRST_NAME varchar2(20) ,
	LAST_NAME varchar2(20) ,
	SPEC VARCHAR(20) ,
	PHONE NUMBER(12),
	SALARY number(10)
);

CREATE table Appointments(
	Appointment_id NUMBER PRIMARY KEY,
	patient_id NUMBER , 
	doctor_id NUMBER ,
	appointment_date DATE,
	Status VARCHAR(255),
	CONSTRAINT con1 FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
	CONSTRAINT con2 FOREIGN KEY (doctor_id) REFERENCES doctors (doctor_id)
);

CREATE TABLE DOCTORS_DEPARTMENT (
    DOCTORS_DEPARTMENT_ID NUMBER(10),
    DOCTOR_ID NUMBER(10),
    DEPARTMENT_ID NUMBER(10),
    CONSTRAINT PK_DOCTORS_DEPARTMENT PRIMARY KEY (DOCTORS_DEPARTMENT_ID, DEPARTMENT_ID),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS_NEW (DEPARTMENT_ID),
    CONSTRAINT FK_DOCTOR FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTORS (DOCTOR_ID)
);

CREATE TABLE PRESCRIPTIONS (
    PRESCRIPTION_ID NUMBER PRIMARY KEY,
    APPOINTMENT_ID NUMBER,
    QUANTITY NUMBER,
    CONSTRAINT FK_APPOINTMENT 
        FOREIGN KEY (APPOINTMENT_ID) 
        REFERENCES APPOINTMENTS (APPOINTMENT_ID)
);
CREATE TABLE ME_PRES (
    ID NUMBER(10) PRIMARY KEY,
    MEDICINE_ID NUMBER(10),
    PRESCRIPTION_ID NUMBER(10),
    CONSTRAINT FK_MEDICINE 
        FOREIGN KEY (MEDICINE_ID) 
        REFERENCES MEDICINES (MEDICINE_ID),
    CONSTRAINT FK_PRESCRIPTION 
        FOREIGN KEY (PRESCRIPTION_ID) 
        REFERENCES PRESCRIPTIONS (PRESCRIPTION_ID)
);

SELECT PATIENTS.first_name , Doctors.fIRST_NAME, APPOINTMENTS.appointment_date FROM APPOINTMENTS
JOIN PATIENTS ON PATIENTS.patient_id = APPOINTMENTS.patient_id
JOIN DOCTORS ON Doctors.doctor_id=APPOINTMENTS.doctor_id;

SELECT p.first_name, COUNT(a.appointment_id)
FROM appointments a
JOIN patients p 
    ON p.patient_id = a.patient_id
GROUP BY p.first_name
HAVING COUNT(a.appointment_id)>1;

SELECT * from doctors d NOT IN (
SELECT dd.DOCTOR_ID FROM DOCTORS_DEPARTMENT dd 
);

SELECT * FROM doctors d JOIN DOCTORS_DEPARTMENT dp 
ON d.doctor_id != dp.doctor_id;






